### ISSUE TITLE
Text direction

### ISSUE THREAD

**Issue by BrandonTheDog** [google/product_video_ads#27]
Hello, hope I'm writing in the right place... 
When adding product titles in a language that it's writing direction is right to left the letters are displayed in a reverse order.  
If I want to have titles in Hebrew or even mixed Hebrew and English it's currently impossible.

**Comment by roberto-goncalves** [comment]
Hi Brandon, this is the right place, could you provide the following: 

- PVA Video Configuration
- PVA Video Result
- How it should behave

Thank you!

**Comment by BrandonTheDog** [comment]
Hi, attched screenshots of
1. product names on google sheets (all in correct order)
2. how it looks when creating the offer types (letters are on correct order, words are not)
3. final outcome (both letters and words are in wrong order)

<img width="263" alt="01 on sheets" src="https://user-images.githubusercontent.com/111688317/188323441-3cd7e064-4858-49df-ba9b-7b067f0a77e9.png">
<img width="779" alt="02 on offer type creation" src="https://user-images.githubusercontent.com/111688317/188323444-d08044a2-436b-4ec8-8262-8c6a0074d43c.png">
<img width="342" alt="03 on exported video2" src="https://user-images.githubusercontent.com/111688317/188323447-d0d7a976-c99b-4203-82cb-965c26b4fa0c.png">
<img width="516" alt="03 on exported video3" src="https://user-images.githubusercontent.com/111688317/188323451-11251634-b1b3-4a28-b02d-89e32cabf060.png">
<img width="533" alt="03 on exported video1" src="https://user-images.githubusercontent.com/111688317/188323456-00284d43-569e-43f5-9d31-66e73625576e.png">

Thanks!
